### ISSUE TITLE
Waschen und Reparieren funktioniert nicht mehr

### ISSUE THREAD

**Issue by Simme-87** [Achimobil/FS25_StaffedWorkshop#1]
Hallo,
Ich wollte gerade meine Geräte und Fahrzeuge instandsetzen und musste dabei leider feststellen das der Trigger nicht mehr Funktioniert.
Es waren Standart FS25 Fahrzeuge.

Screenshot:
![fsScreen_2024_12_01_09_25_20](https://github.com/user-attachments/assets/a8081670-27c4-4df5-974b-b12711c523d3)

Im Log habe folgenden Error:
2024-12-01 08:55 Error: Running LUA method 'onTriggerCallback'.
D:/Documents/My Games/FarmingSimulator2025/mods/FS25_StuffedWorkshop/scripts/AutomaticCarWash.lua:191: attempt to index nil with 'getDirtAmount'

Hier auch nochmal die Vollständige Log Datei für den Fall das diese benötigt wird.
[log.txt](https://github.com/user-attachments/files/17968246/log.txt)

**Comment by Achimobil** [comment]
Der Fehler sagt, dass im Trigger sich zwar ein Fahrzeug befindet, dieses kann die Engine aber nicht.
Sehr merkwürdig und nicht so wirklich verständlich. Aber durch die Log kann ich ihn abstellen und checke das im Main ein.
Da bisher sonst nicht aufgetreten werde ich die eingereichte ModHub Version nicht zurück ziehen damit es mit dem Testen nicht noch länger dauert, werde es aber, sollte er wegen irgendwas zurück kommen, mit einreichen.

**Comment by Simme-87** [comment]
Gerade deine korrigierte Version geladen und getestet. Die funktioniert nun wieder. Danke fürs Schnelle Reagieren.

**Comment by Achimobil** [comment]
Gern, wie immer ;)

**Comment by Achimobil** [comment]
Da ich neu einreichen musste ist der fix da jetzt mit drin in der 1.0.0.0 für den ModHub
